services:
  - type: web
    name: yelpcamp-problem-discovery
    env: node
    buildCommand: npm install
    startCommand: node app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_URL
        sync: false
      - key: SECRET
        sync: false
      - key: HUGGINGFACE_API_KEY
        sync: false 